'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18033
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Explosive_Game_Maker.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property create() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("create", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property debug() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("debug", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property egm_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("egm_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property egm_folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("egm_folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property egm_start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("egm_start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property egm_stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("egm_stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Option Strict On
        '''Imports System
        '''Imports System.Windows.Forms
        '''Imports System.Windows.Forms.Form
        '''Imports System.Windows.Forms.Button
        '''Imports System.Windows.Forms.Application
        '''Imports System.Windows.Forms.PaintEventArgs
        '''Imports Microsoft.VisualBasic
        '''Imports System.Drawing
        '''Imports System.Drawing.Image
        '''Imports System.Drawing.Bitmap
        '''Imports System.Diagnostics.Process
        '''Imports System.IO.DirectoryInfo
        '''Imports System.IO.FileInfo
        '''Imports System.IO.Path
        '''Imports System.IO.StreamReader
        '''Imports System.Coll [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property EGMCore1() As String
            Get
                Return ResourceManager.GetString("EGMCore1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;
        '''.
        '''</summary>
        Friend ReadOnly Property EGMCore2() As String
            Get
                Return ResourceManager.GetString("EGMCore2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''
        '''
        '''&apos;Core functions
        '''
        '''    Private Sub Me_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        '''        Me.KeyPreview = True
        '''    End Sub
        '''	
        '''    Public CallLeftUp As String = &quot;LeftUp&quot;
        '''    Public CallRightUp As String = &quot;RightUp&quot;
        '''    Public CallDownUp As String = &quot;DownUp&quot;
        '''    Public CallUpUp As String = &quot;UpUp&quot;
        '''    Public CallLeftDown As String = &quot;LeftDown&quot;
        '''    Public CallRightDown As String = &quot;RightDown&quot;
        '''    Public CallDownDown As String = &quot;DownDown&quot;
        '''    Public CallUpDown As String = &quot;UpDown&quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property EGMCore3() As String
            Get
                Return ResourceManager.GetString("EGMCore3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''
        '''End Sub
        '''&apos;Dec will go here.
        '''</summary>
        Friend ReadOnly Property EGMCore4() As String
            Get
                Return ResourceManager.GetString("EGMCore4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to End Class
        '''&apos;script to go here now.....
        '''</summary>
        Friend ReadOnly Property EGMCore5() As String
            Get
                Return ResourceManager.GetString("EGMCore5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EGMCreate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EGMCreate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EGMDebug() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EGMDebug", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EGMStop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EGMStop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property script() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("script", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Room_Height,CornflowerBlue
        '''Room_Width,CornflowerBlue
        '''Room_Dimension,CornflowerBlue
        '''Score,CornflowerBlue
        '''DrawScore,CornflowerBlue
        '''Draw_Sprite,CornflowerBlue
        '''Lives(),CornflowerBlue
        '''&quot;SET&quot;,LightGreen
        '''&quot;GET&quot;,LightGreen
        '''xScore,Indigo
        '''xLives,Indigo
        '''lblLives,Indigo.
        '''</summary>
        Friend ReadOnly Property Tokens() As String
            Get
                Return ResourceManager.GetString("Tokens", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
